# Generated by Django 2.2.3 on 2019-07-25 01:27

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator])),
                ('last_sent_time', models.DateTimeField(auto_now_add=True)),
                ('retries', models.PositiveSmallIntegerField(default=0)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirm_code', models.CharField(max_length=6)),
            ],
        ),
    ]
