# Generated by Django 2.2.3 on 2019-07-24 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_number', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumber',
            old_name='retires',
            new_name='retries',
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='confirm_code',
            field=models.CharField(default='213121', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='phone_number',
            field=models.CharField(default=123456, max_length=14, validators=[django.core.validators.RegexValidator]),
            preserve_default=False,
        ),
    ]
