# Generated by Django 2.2.3 on 2019-08-21 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_number', '0003_auto_20190725_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'ordering': ['-last_sent_time']},
        ),
    ]
