version: '3'

services: 
  api:
    build: ./api
    container_name: 'api'
    volumes:
      - ./api:/code
      - static:/static  
      - media:/media 
    environment:
      - DJANGO_CONFIGURATION
    depends_on: 
      - postgres
      # - logstash
    env_file: ./.env
    networks:
      - nginx_network
      - db-network

  redis:
    image: "redis:alpine"
    networks:
        - nginx_network

  celery:
    build: ./api
    command: >
      bash -c "celery -A api worker -l info"
    volumes:
      - ./api:/code
    environment:
      - DJANGO_CONFIGURATION
    env_file: ./.env
    depends_on:
      - postgres
      - redis
    networks:
      - nginx_network

  celery-beat:
    build: ./api
    command: >
      bash -c "celery -A api beat -l info"
    volumes:
      - ./api:/code
    environment:
      - DJANGO_CONFIGURATION
    env_file: ./.env
    depends_on:
      - postgres
      - redis
    networks:
      - nginx_network

  postgres:
    image: postgres:11.4
    container_name: 'postgres'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: ./.env
    networks:
      - db-network

  # elasticsearch:
  #   build:
  #     context: elasticsearch/
  #     args:
  #       ELK_VERSION: $ELK_VERSION
  #   volumes:
  #     - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
  #     - elasticsearch:/usr/share/elasticsearch/data
  #   # ports:
  #   #   - "9200:9200"
  #   #   - "9300:9300"
  #   expose: 
  #     - "9200"
  #     - "9300"
  #   environment:
  #     ES_JAVA_OPTS: "-Xmx256m -Xms256m"
  #     ELASTIC_PASSWORD: changeme

  # logstash:
  #   container_name: 'logstash'
  #   build:
  #     context: logstash/
  #     args:
  #       ELK_VERSION: $ELK_VERSION
  #   volumes:
  #     - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
  #     - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
  #   # ports:
  #   #   - "5000:5000"
  #   #   - "9600:9600"
  #   expose: 
  #     - "5000"
  #     - "9600"
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx256m -Xms256m"

  #   depends_on:
  #     - elasticsearch

  # kibana:
  #   build:
  #     context: kibana/
  #     args:
  #       ELK_VERSION: $ELK_VERSION
  #   volumes:
  #     - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     - elasticsearch

volumes:
  postgres_data:
  static:
  media:
  # elasticsearch:
      
networks:
  nginx_network:
    driver: bridge
  db-network:
    driver: bridge