version: '3'

services: 
  api:
    ports: 
      - "3200:8000"
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    
