version: '3'

services: 
  api:
    build: ./api
    container_name: 'api'
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    depends_on: 
      - postgres
      - logstash
    volumes: 
      - ./api:/code
    env_file: ./.env
  redis:
    image: "redis:alpine"

  celery:
    build: ./api
    command: >
      bash -c "celery -A api worker -l info"
    volumes:
      - ./api:/code
    env_file: ./.env
    depends_on:
      - postgres
      - redis

  celery-beat:
    build: ./api
    command: >
      bash -c "celery -A api beat -l infos"
    volumes:
      - ./api:/code
    env_file: ./.env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:11.4
    container_name: 'postgres'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: ./.env

  # elasticsearch:
  #   build:
  #     context: elasticsearch/
  #     args:
  #       ELK_VERSION: $ELK_VERSION
  #   volumes:
  #     - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
  #     - elasticsearch:/usr/share/elasticsearch/data
  #   # ports:
  #   #   - "9200:9200"
  #   #   - "9300:9300"
  #   expose: 
  #     - "9200"
  #     - "9300"
  #   environment:
  #     ES_JAVA_OPTS: "-Xmx256m -Xms256m"
  #     ELASTIC_PASSWORD: changeme

  # logstash:
  #   container_name: 'logstash'
  #   build:
  #     context: logstash/
  #     args:
  #       ELK_VERSION: $ELK_VERSION
  #   volumes:
  #     - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
  #     - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
  #   # ports:
  #   #   - "5000:5000"
  #   #   - "9600:9600"
  #   expose: 
  #     - "5000"
  #     - "9600"
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx256m -Xms256m"

  #   depends_on:
  #     - elasticsearch

  # kibana:
  #   build:
  #     context: kibana/
  #     args:
  #       ELK_VERSION: $ELK_VERSION
  #   volumes:
  #     - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     - elasticsearch

volumes:
  postgres_data:
  # elasticsearch:
      