# Generated by Django 2.2.3 on 2019-07-24 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator]),
        ),
    ]
