# Generated by Django 2.2.3 on 2019-09-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='lat',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='long',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
