# Generated by Django 2.2.3 on 2019-07-26 01:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('suggests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basesuggest',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
