# Generated by Django 2.2.3 on 2019-08-21 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggests', '0002_basesuggest_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowsuggest',
            name='price',
        ),
        migrations.RemoveField(
            model_name='lendsuggest',
            name='price_per_day',
        ),
    ]
