# Generated by Django 2.2.3 on 2019-07-25 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseFeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lat', models.DecimalField(db_index=True, decimal_places=4, max_digits=6)),
                ('long', models.DecimalField(db_index=True, decimal_places=4, max_digits=6)),
                ('game', models.CharField(max_length=100)),
                ('console', models.CharField(choices=[('PS', 'PS4'), ('XB', 'XBOX'), ('PA', 'PS3')], default='PS', max_length=2)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_feeds.basefeed_set+', to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_time'],
            },
        ),
        migrations.CreateModel(
            name='BorrowFeed',
            fields=[
                ('basefeed_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feeds.BaseFeed')),
                ('duration', models.PositiveSmallIntegerField()),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('feeds.basefeed',),
        ),
        migrations.CreateModel(
            name='LendFeed',
            fields=[
                ('basefeed_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feeds.BaseFeed')),
                ('need_id', models.BooleanField(default=True)),
                ('price_per_day', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('feeds.basefeed',),
        ),
    ]
