# Generated by Django 2.2.3 on 2019-07-25 01:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowFeed',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lat', models.DecimalField(db_index=True, decimal_places=4, max_digits=6)),
                ('long', models.DecimalField(db_index=True, decimal_places=4, max_digits=6)),
                ('game', models.CharField(max_length=100)),
                ('console', models.CharField(choices=[('PS', 'PS4'), ('XB', 'XBOX'), ('PA', 'PS3')], default='PS', max_length=2)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('duration', models.PositiveSmallIntegerField()),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['created_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LendFeed',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lat', models.DecimalField(db_index=True, decimal_places=4, max_digits=6)),
                ('long', models.DecimalField(db_index=True, decimal_places=4, max_digits=6)),
                ('game', models.CharField(max_length=100)),
                ('console', models.CharField(choices=[('PS', 'PS4'), ('XB', 'XBOX'), ('PA', 'PS3')], default='PS', max_length=2)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('need_id', models.BooleanField(default=True)),
                ('price_per_day', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['created_time'],
                'abstract': False,
            },
        ),
    ]
