# Generated by Django 2.2.3 on 2019-07-27 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_reportfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfeed',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='feeds.BaseFeed'),
        ),
    ]
