# Generated by Django 2.2.3 on 2019-08-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_auto_20190822_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basefeed',
            name='lat',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='basefeed',
            name='long',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
