# Generated by Django 2.2.3 on 2019-09-13 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_auto_20190825_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basefeed',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='basefeed',
            name='long',
        ),
    ]
